// lintHtml — soxta xatolar / o'tkazib yuborishlar / satr raqami
import { open } from './tc-lib.mjs';
const { b, p } = await open();
// [nom, html, kutilgan xatolar soni (yoki 'note'), izoh]
const CASES = [
  // to'g'ri HTML — 0 xato kutiladi
  ['ok: oddiy', '<h1>Salom</h1>', 0],
  ['ok: bo\'sh', '', 0],
  ['ok: faqat matn', 'salom dunyo', 0],
  ['ok: doctype+html', '<!DOCTYPE html>\n<html>\n<head><title>x</title></head>\n<body><h1>x</h1></body>\n</html>', 0],
  ['ok: <ul><li>a<li>b</ul>', '<ul><li>a<li>b</ul>', 0],
  ['ok: <ul><li>a</li><li>b</li></ul>', '<ul><li>a</li><li>b</li></ul>', 0],
  ['ok: <p>a<p>b', '<p>a<p>b', 0],
  ['ok: <p>a<div>b</div>', '<p>a<div>b</div>', 0],
  ['ok: <p>a</p><div>b</div>', '<p>a</p><div>b</div>', 0],
  ['ok: <p><b>x</b></p>', '<p><b>x</b></p>', 0],
  ['ok: <br>', 'a<br>b', 0],
  ['ok: <br/>', 'a<br/>b', 0],
  ['ok: <br />', 'a<br />b', 0],
  ['ok: <img src="a" alt="b">', '<img src="a" alt="b">', 0],
  ['ok: <img ... />', '<img src="a" alt="b" />', 0],
  ['ok: <input>', '<input type="text">', 0],
  ['ok: <hr>', '<hr>', 0],
  ['ok: <meta>', '<head><meta charset="utf-8"></head>', 0],
  ['ok: <link>', '<link rel="stylesheet" href="x.css">', 0],
  ['ok: izoh', '<!-- <h1>x</h1> -->', 0],
  ['ok: izoh ichida yopilmagan teg', '<!-- <h1>x -->', 0],
  ['ok: izoh ichida > belgisi', '<!-- a > b -->', 0],
  ['ok: izoh ichida -- ', '<!-- a -- b -->', 0],
  ['ok: atributda >', '<a title="a > b">x</a>', 0],
  ['ok: atributda <', '<a title="a < b">x</a>', 0],
  ['ok: atributda </a>', '<a title="</a>">x</a>', 0],
  ['ok: bir tirnoq ichida ikki tirnoq', "<a title='say \"hi\"'>x</a>", 0],
  ['ok: ikki tirnoq ichida bir tirnoq', '<a title="it\'s">x</a>', 0],
  ['ok: matnda apostrof', "<p>it's ok</p>", 0],
  ['ok: matnda tirnoq', '<p>u "quoted"</p>', 0],
  ['ok: matnda < probel', '<p>2 < 3</p>', 0],
  ['ok: matnda a<b (harf keyin)', '<p>a<b</p>', 'note'],
  ['ok: entity &lt;h1&gt;', '<p>&lt;h1&gt;</p>', 0],
  ['ok: <script> ichida <', '<script>if(a<b){x="<div>"}</script>', 'note'],
  ['ok: <script> ichida </div> satr', '<script>var s="</div>";</script>', 'note'],
  ['ok: <script> ichida "<h1>"', '<script>document.write("<h1>x</h1>")</script>', 'note'],
  ['ok: <script> ichida "<h1>" yopilmagan', '<script>document.write("<h1>x")</script>', 'note'],
  ['ok: <script> ichida for(i<3)', '<script>for(var i=0;i<3;i++){}</script>', 'note'],
  ['ok: <script> ichida a<b regex', '<script>if(a<b && c>d){}</script>', 'note'],
  ['ok: <style> ichida a>b', '<style>a>b{color:red}</style>', 'note'],
  ['ok: <style> ichida <', '<style>/* < */</style>', 'note'],
  ['ok: <textarea> ichida <h1>', '<textarea><h1>x</textarea>', 'note'],
  ['ok: <pre> ichida', '<pre>a\n b</pre>', 0],
  ['ok: <table> to\'liq', '<table><tr><td>1</td><td>2</td></tr></table>', 0],
  ['ok: <table> ixtiyoriy yopilgan', '<table><tr><td>1<td>2<tr><td>3</table>', 0],
  ['ok: <table><thead><tr><th>a</th></tr></thead><tbody><tr><td>b</td></tr></tbody></table>', '<table><thead><tr><th>a</th></tr></thead><tbody><tr><td>b</td></tr></tbody></table>', 0],
  ['ok: <table><thead><tr><th>a<tbody><tr><td>b</table>', '<table><thead><tr><th>a<tbody><tr><td>b</table>', 0],
  ['ok: <select><option>a<option>b</select>', '<select><option>a<option>b</select>', 0],
  ['ok: <dl><dt>a<dd>b<dt>c<dd>d</dl>', '<dl><dt>a<dd>b<dt>c<dd>d</dl>', 0],
  ['ok: <ul><li><p>a<li>b</ul>', '<ul><li><p>a<li>b</ul>', 0],
  ['ok: <li> ichida <ul><li>', '<ul><li>a<ul><li>b</ul><li>c</ul>', 0],
  ['ok: <li> ichida <ul><li> (yopilgan)', '<ul><li>a<ul><li>b</li></ul></li><li>c</li></ul>', 0],
  ['ok: <p> ichida <a>', '<p><a href="#">x</a></p>', 0],
  ['ok: <p><img></p>', '<p><img src="a" alt="b"></p>', 0],
  ['ok: <p><br></p>', '<p><br></p>', 0],
  ['ok: <p> yopilmay <ul>', '<p>a<ul><li>b</ul>', 0],
  ['ok: <p> yopilmay <h1>', '<p>a<h1>b</h1>', 0],
  ['ok: <p> yopilmay <table>', '<p>a<table><tr><td>b</table>', 0],
  ['ok: <p> yopilmay </div>', '<div><p>a</div>', 0],
  ['ok: <p> yopilmay </section>', '<section><p>a</section>', 0],
  ['ok: <p> yopilmay </body>', '<body><p>a</body>', 0],
  ['ok: <li> yopilmay </ol>', '<ol><li>a</ol>', 0],
  ['ok: <td> yopilmay </table>', '<table><tr><td>a</table>', 0],
  ['ok: <option> yopilmay </select>', '<select><option>a</select>', 0],
  ['ok: <html><head><body> yopilmagan (ixtiyoriy)', '<!doctype html><html><head><title>x</title><body><h1>x</h1>', 'note'],
  ['ok: <html> ichida <body> yopilmagan', '<html><body><h1>x</h1></html>', 'note'],
  ['ok: <head> yopilmagan', '<head><title>x</title><body>x</body>', 'note'],
  ['ok: katta harf <H1></H1>', '<H1>x</H1>', 0],
  ['ok: aralash <h1></H1>', '<h1>x</H1>', 0],
  ['ok: <h1 > probel', '<h1 >x</h1 >', 0],
  ['ok: </h1 > probel', '<h1>x</h1 >', 0],
  ['ok: atribut qatorlarga bo\'lingan', '<img\n  src="a"\n  alt="b"\n>', 0],
  ['ok: tirnoqsiz atribut', '<a href=x.html>x</a>', 0],
  ['ok: tirnoqsiz atribut ichida /', '<a href=a/b>x</a>', 0],
  ['ok: tirnoqsiz atribut ichida / oxirida', '<a href=a/>x</a>', 'note'],
  ['ok: bo\'sh atribut', '<input disabled>', 0],
  ['ok: bo\'sh atribut / bilan', '<input disabled/>', 0],
  ['ok: data-* atribut', '<div data-x="1">x</div>', 0],
  ['ok: custom element', '<my-el>x</my-el>', 0],
  ['ok: svg', '<svg><circle cx="1" cy="1" r="1"/></svg>', 0],
  ['ok: svg <path d="..."/>', '<svg viewBox="0 0 10 10"><path d="M0 0L10 10"/></svg>', 0],
  ['ok: <template>', '<template><h1>x</h1></template>', 0],
  ['ok: uzun matn qatorlar', 'a\nb\nc\n<h1>x</h1>', 0],
  ['ok: emoji', '<p>😀</p>', 0],
  ['ok: kirill', '<p>Салом</p>', 0],
  ['ok: <a> ichida <img>', '<a href="#"><img src="a" alt="b"></a>', 0],
  ['ok: <button> ichida <span>', '<button><span>x</span></button>', 0],
  ['ok: <label><input></label>', '<label>x<input></label>', 0],
  ['ok: <form> to\'liq', '<form action="/x"><input name="a"><button>ok</button></form>', 0],
  ['ok: <div><div><div>', '<div><div><div>x</div></div></div>', 0],
  ['ok: matn ichida <3', '<p>I <3 HTML</p>', 0],
  ['ok: matn ichida < oxirida', '<p>a <</p>', 'note'],
  ['ok: matn ichida <=', '<p>a <= b</p>', 0],
  ['ok: matn ichida <-', '<p>a <- b</p>', 0],
  ['ok: matn ichida <!', '<p>a <! b</p>', 'note'],
  ['ok: matn ichida <?', '<p>a <? b</p>', 'note'],
  ['ok: matn ichida <?xml', '<?xml version="1.0"?><h1>x</h1>', 'note'],
  ['ok: CDATA', '<![CDATA[ x ]]><h1>x</h1>', 'note'],
  ['ok: <!-- --> ichida <!--', '<!-- <!-- x --><h1>x</h1>', 'note'],
  ['ok: <!---->', '<!----><h1>x</h1>', 'note'],
  ['ok: <!--->', '<!---><h1>x</h1>', 'note'],
  ['ok: <!-->', '<!--><h1>x</h1>', 'note'],
  ['ok: ichma-ich <p><p> (2 xato emas)', '<p><p>x</p></p>', 'note'],
  ['ok: <a> ichida <a>', '<a><a>x</a></a>', 'note'],
  ['ok: <ul><li>a</li>b</ul>', '<ul><li>a</li>b</ul>', 0],
  ['ok: <ul><ul><li>', '<ul><ul><li>x</li></ul></ul>', 0],
  ['ok: bo\'sh h1 <h1></h1>', '<h1></h1>', 0],
  ['ok: <script src=x></script>', '<script src="x.js"></script>', 0],
  ['ok: <script></script> ichida <!--', '<script><!--\nvar a=1;\n//--></script>', 'note'],
  ['ok: <style> ichida <!--', '<style><!--\nh1{}\n--></style>', 'note'],
  ['ok: <script> ichida "</scr"+"ipt>"', '<script>var s="</scr"+"ipt>";</script>', 'note'],
  ['ok: <script> ichida `<`', '<script>let x = a<b?1:2;</script>', 'note'],
  ['ok: <script> ichida "<!--"', '<script>var s="<!--";</script>', 'note'],
  ['ok: <script> ichida </p>', '<script>el.innerHTML="<p>a</p>";</script>', 'note'],
  ['ok: <script> ichida "<p>a" yopilmagan', '<script>el.innerHTML="<p>a";</script>', 'note'],
  ['ok: <script> ichida "<div>a" yopilmagan', '<script>el.innerHTML="<div>a";</script>', 'note'],
  ['ok: <script> ichida "</div>" ochilmagan', '<script>el.innerHTML="</div>";</script>', 'note'],
  ['ok: <script> ichida "<img src=x>"', '<script>el.innerHTML="<img src=x>";</script>', 'note'],
  ['ok: <script> ichida "<b>x</b>"', '<script>el.innerHTML="<b>x</b>";</script>', 'note'],
  ['ok: <script> ichida "<b>x"', '<script>el.innerHTML="<b>x";</script>', 'note'],
  ['ok: <script> ichida "x</b>"', '<script>el.innerHTML="x</b>";</script>', 'note'],
  ['ok: <script> ichida `<a href="#">`', '<script>el.innerHTML=`<a href="#">x</a>`;</script>', 'note'],
  ['ok: <script> ichida `<a href="#">` yopilmagan', '<script>el.innerHTML=`<a href="#">x`;</script>', 'note'],
  ['ok: <script> ichida "<"', '<script>var s="<";</script>', 'note'],
  ['ok: <script> ichida "<a"', '<script>var s="<a";</script>', 'note'],
  ['ok: <script> ichida "<a "', '<script>var s="<a ";</script>', 'note'],
  ['ok: <script> ichida "<a>"', '<script>var s="<a>";</script>', 'note'],
  ['ok: <script> ichida `<a`', '<script>var s=`<a`;</script>', 'note'],
  ['ok: <script> ichida a<b>c', '<script>if(a<b>c){}</script>', 'note'],
  ['ok: <script> ichida a<b>c yopilgan', '<script>if(a<b>c</b>){}</script>', 'note'],
  ['ok: <script> ichida "\'"', "<script>var s=\"'\";</script>", 'note'],
  ['ok: <script> ichida "\'" + <', "<script>var s=\"'\"; if(a<b){}</script>", 'note'],
  ['ok: <script> ichida \'"\' + <', '<script>var s=\'"\'; if(a<b){}</script>', 'note'],
  ['ok: <script> ichida x<y va \'', "<script>if(x<y){s='a'}</script>", 'note'],
  ['ok: <script> ichida x<y va \' juft', "<script>if(x<y){s='a';t='b'}</script>", 'note'],
  ['ok: <script> ichida x<y va " juft', '<script>if(x<y){s="a";t="b"}</script>', 'note'],
  ['ok: <script> ichida x<y va " toq', '<script>if(x<y){s="a"}</script>', 'note'],
  ['ok: <script> ichida x<y va " toq va >', '<script>if(x<y){s="a>"}</script>', 'note'],
  ['ok: <script> ichida x<y va " juft va >', '<script>if(x<y){s="a>";t="b"}</script>', 'note'],
  ['ok: <script> ichida x<yz va " juft va >', '<script>if(x<yz){s="a>";t="b"}</script>', 'note'],
  ['ok: <script> ichida x <y va " juft va >', '<script>if(x <y){s="a>";t="b"}</script>', 'note'],
  ['ok: <script> ichida x< y va " juft va >', '<script>if(x< y){s="a>";t="b"}</script>', 'note'],
  ['ok: <script> ichida x<1', '<script>if(x<1){}</script>', 'note'],
  ['ok: <script> ichida x<-1', '<script>if(x<-1){}</script>', 'note'],
  ['ok: <script> ichida x<(1)', '<script>if(x<(1)){}</script>', 'note'],
  ['ok: <script> ichida x<"a"', '<script>if(x<"a"){}</script>', 'note'],
  ['ok: <script> ichida x<a.length', '<script>for(i=0;i<a.length;i++){}</script>', 'note'],
  ['ok: <script> ichida x<a.length va >', '<script>for(i=0;i<a.length;i++){if(a>b){}}</script>', 'note'],
  ['ok: <script> ichida x<a.length va > va "', '<script>for(i=0;i<a.length;i++){if(a>b){s="x"}}</script>', 'note'],
  ['ok: <script> ichida x<a.length va > va " toq', '<script>for(i=0;i<a.length;i++){if(a>b){s="x}}</script>', 'note'],
  ['ok: <script> ichida x<a.length va > va \' toq', "<script>for(i=0;i<a.length;i++){if(a>b){s='x}}</script>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}</script>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x</h1>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1 yopilmagan', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1 yopilmagan va </p>', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x</p>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1 yopilmagan va </p> va </h1>', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x</p></h1>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1 yopilmagan va </p> va </h1> va </script>', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x</p></h1></script>", 'note'],
  ['ok: <script> ichida x<a.length va > va \' juft va </script> yo\'q va h1 yopilmagan va </p> va </h1> va </script> va h2', "<script>for(i=0;i<a.length;i++){if(a>b){s='x'}}<h1>x</p></h1></script><h2>y</h2>", 'note'],
  // xatolar — kamida 1 kutiladi
  ['err: yopilmagan <h1>', '<h1>x', 1],
  ['err: <h1>x</h2>', '<h1>x</h2>', 'note'],
  ['err: <h1>x</h1></h1>', '<h1>x</h1></h1>', 1],
  ['err: </h1> yolg\'iz', '</h1>', 1],
  ['err: <div><p>x</div></p>', '<div><p>x</div></p>', 'note'],
  ['err: <b><i>x</b></i>', '<b><i>x</b></i>', 'note'],
  ['err: <ul><li>a</ul></li>', '<ul><li>a</ul></li>', 'note'],
  ['err: <h1 class="x>y</h1>', '<h1 class="x>y</h1>', 'note'],
  ['err: <h1 class="x">y</h1', '<h1 class="x">y</h1', 'note'],
  ['err: <h1 class="x">y<h1', '<h1 class="x">y<h1', 'note'],
  ['err: <h1', '<h1', 'note'],
  ['err: <h1 ', '<h1 ', 'note'],
  ['err: <h1 <p>', '<h1 <p>x</p>', 'note'],
  ['err: <img src="a" alt="b"', '<img src="a" alt="b"', 'note'],
  ['err: <img src="a alt="b">', '<img src="a alt="b">', 'note'],
  ['err: <img src=a alt=b', '<img src=a alt=b', 'note'],
  ['err: <!-- yopilmagan', '<!-- x', 'note'],
  ['err: <!-- yopilmagan + teg', '<!-- x\n<h1>y</h1>', 'note'],
  ['err: <! yopilmagan', '<!doctype html', 'note'],
  ['err: <div>\n<p>x\n</span>\n</div>', '<div>\n<p>x\n</span>\n</div>', 'note'],
  ['err: <div>\n<span>x\n</div>', '<div>\n<span>x\n</div>', 'note'],
  ['err: <div>\n<span>x\n</div>\n</span>', '<div>\n<span>x\n</div>\n</span>', 'note'],
  ['err: <ul>\n<li>a\n<li>b\n</ol>', '<ul>\n<li>a\n<li>b\n</ol>', 'note'],
  ['err: <ul>\n<li>a</li>\n<li>b</li>', '<ul>\n<li>a</li>\n<li>b</li>', 'note'],
  ['err: <ul><li>a</li><li>b</li></u>', '<ul><li>a</li><li>b</li></u>', 'note'],
  ['err: <ul><li>a</li><li>b</li></lu>', '<ul><li>a</li><li>b</li></lu>', 'note'],
  ['err: <h1>x<h1>', '<h1>x<h1>', 'note'],
  ['err: <p>x<p>y</p> — 2 ta p, 1 ta yopilgan', '<p>x<p>y</p>', 'note'],
  ['err: <div>x<div>y</div>', '<div>x<div>y</div>', 'note'],
  ['err: <div>x<div>y</div> satr raqami', '<div>x\n<div>y</div>', 'note'],
  ['err: <span>a<div>b</div></span>', '<span>a<div>b</div></span>', 'note'],
  ['err: <a>a<div>b</div></a>', '<a>a<div>b</div></a>', 'note'],
  ['err: <p><div>x</div></p>', '<p><div>x</div></p>', 'note'],
  ['err: <p><h1>x</h1></p>', '<p><h1>x</h1></p>', 'note'],
  ['err: <p><ul><li>a</li></ul></p>', '<p><ul><li>a</li></ul></p>', 'note'],
  ['err: <li>a</li> <ul> siz', '<li>a</li>', 'note'],
  ['err: <td> <table> siz', '<td>a</td>', 'note'],
  ['err: <img>x</img>', '<img src="a">x</img>', 'note'],
  ['err: <br></br>', 'a<br></br>b', 'note'],
  ['err: <input></input>', '<input></input>', 'note'],
  ['err: </br>', 'a</br>b', 'note'],
  ['err: <hr>x</hr>', '<hr>x</hr>', 'note'],
  ['err: <h1/>x', '<h1/>x', 'note'],
  ['err: <div/>x', '<div/>x', 'note'],
  ['err: <p/>x', '<p/>x', 'note'],
  ['err: <span/>x', '<span/>x', 'note'],
  ['err: <a href="#"/>x', '<a href="#"/>x', 'note'],
  ['err: <script/>', '<script/>alert(1)', 'note'],
  ['err: <div><div></div>', '<div><div></div>', 'note'],
  ['err: <div></div></div>', '<div></div></div>', 'note'],
  ['err: <h1>a<b>b</h1>', '<h1>a<b>b</h1>', 'note'],
  ['err: <h1>a<b>b</h1> </b>', '<h1>a<b>b</h1></b>', 'note'],
  ['err: <b>a<h1>b</b></h1>', '<b>a<h1>b</b></h1>', 'note'],
  ['err: <table><tr><td>a</tr></td></table>', '<table><tr><td>a</tr></td></table>', 'note'],
  ['err: <table><td>a</td></table> (tr yo\'q)', '<table><td>a</td></table>', 'note'],
  ['err: <ul><p>a</p></ul>', '<ul><p>a</p></ul>', 'note'],
  ['err: <html><body></html></body>', '<html><body></html></body>', 'note'],
  ['err: <html><body></body></html></html>', '<html><body></body></html></html>', 'note'],
  ['err: <h1>x</h1>\n<p>y\n</h1>', '<h1>x</h1>\n<p>y\n</h1>', 'note'],
  ['err: <h1>x</h1>\n<p>y</p>\n</h1>', '<h1>x</h1>\n<p>y</p>\n</h1>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>\n</h1>\n</div>', '<div>\n<h1>x</h1>\n<p>y</p>\n</h1>\n</div>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>\n</div>\n</div>', '<div>\n<h1>x</h1>\n<p>y</p>\n</div>\n</div>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>', '<div>\n<h1>x</h1>\n<p>y</p>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>\n<div>', '<div>\n<h1>x</h1>\n<p>y</p>\n<div>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>\n<div>\n</div>', '<div>\n<h1>x</h1>\n<p>y</p>\n<div>\n</div>', 'note'],
  ['err: <div>\n<h1>x</h1>\n<p>y</p>\n<div>\n</div>\n</div>\n</div>', '<div>\n<h1>x</h1>\n<p>y</p>\n<div>\n</div>\n</div>\n</div>', 'note'],
  ['err: <div>\n<h1>x\n<p>y</p>\n</div>', '<div>\n<h1>x\n<p>y</p>\n</div>', 'note'],
  ['err: <div>\n<h1>x\n<p>y</p>\n</div> — satr 2 kutiladi', '<div>\n<h1>x\n<p>y</p>\n</div>', 'note'],
  ['err: <div>\n<h1>x\n<h1>y</h1>\n</div>', '<div>\n<h1>x\n<h1>y</h1>\n</div>', 'note'],
  ['err: <div>\n<h1>x\n<h1>y</h1>\n</div>\n</h1>', '<div>\n<h1>x\n<h1>y</h1>\n</div>\n</h1>', 'note'],
  ['err: <div>\n<a>x\n</a>\n</div>\n</a>', '<div>\n<a>x\n</a>\n</div>\n</a>', 'note'],
  ['err: <div>\n<a>x\n</div>\n</a>', '<div>\n<a>x\n</div>\n</a>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</div>', '<div>\n<a>x\n</span>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</div>\n</a>', '<div>\n<a>x\n</span>\n</div>\n</a>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>\n</div>', 'note'],
  ['err: <div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>\n</div>\n</div>', '<div>\n<a>x\n</span>\n</a>\n</div>\n</span>\n</div>\n</a>\n</h1>\n<h1>y</h1>\n</div>\n<div>\n</div>\n</div>\n</div>', 'note'],
  ['err: <p>x</P>', '<p>x</P>', 0],
  ['err: <p>x</ p>', '<p>x</ p>', 'note'],
  ['err: <p>x< /p>', '<p>x< /p>', 'note'],
  ['err: <p>x</p >', '<p>x</p >', 0],
  ['err: <p>x</p/>', '<p>x</p/>', 'note'],
  ['err: <p>x</>', '<p>x</>', 'note'],
  ['err: <>x</>', '<>x</>', 'note'],
  ['err: <1>x</1>', '<1>x</1>', 'note'],
  ['err: <-a>x</-a>', '<-a>x</-a>', 'note'],
  ['err: <_a>x</_a>', '<_a>x</_a>', 'note'],
  ['err: <a_b>x</a_b>', '<a_b>x</a_b>', 'note'],
  ['err: <a:b>x</a:b>', '<a:b>x</a:b>', 'note'],
  ['err: <a.b>x</a.b>', '<a.b>x</a.b>', 'note'],
  ['err: <a=b>x</a=b>', '<a=b>x</a=b>', 'note'],
  ['err: <a"b>x</a"b>', '<a"b>x</a"b>', 'note'],
  ['err: <h1>x</h1>x</h1>', '<h1>x</h1>x</h1>', 'note'],
  ['err: <div>\n<h1>x</h1>\n</div>\n<p>y\n<h1>z</h1>\n</p>', '<div>\n<h1>x</h1>\n</div>\n<p>y\n<h1>z</h1>\n</p>', 'note'],
  ['err: <div>\n<h1>x</h1>\n</div>\n<p>y\n<h1>z</h1>', '<div>\n<h1>x</h1>\n</div>\n<p>y\n<h1>z</h1>', 0],
  ['err: <p>y\n</p>\n</p>', '<p>y\n</p>\n</p>', 'note'],
  ['err: <p>y\n<div>\n</p>\n</div>', '<p>y\n<div>\n</p>\n</div>', 'note'],
  ['err: <p>y\n<b>\n</p>\n</b>', '<p>y\n<b>\n</p>\n</b>', 'note'],
  ['err: <p>y\n<b>z\n</p>', '<p>y\n<b>z\n</p>', 'note'],
  ['err: <p><b>z</p>', '<p><b>z</p>', 'note'],
  ['err: <b><p>z</b>', '<b><p>z</b>', 'note'],
  ['err: <b><p>z</b></p>', '<b><p>z</b></p>', 'note'],
  ['err: <li><p>z</li>', '<ul><li><p>z</li></ul>', 0],
  ['err: <li><b>z</li>', '<ul><li><b>z</li></ul>', 'note'],
  ['err: <li><b>z</li></b>', '<ul><li><b>z</li></b></ul>', 'note'],
  ['err: <li><div>z</li>', '<ul><li><div>z</li></ul>', 'note'],
  ['err: <li><div>z</li></ul>', '<ul><li><div>z</li></ul>', 'note'],
  ['err: <li>z<div></li>', '<ul><li>z<div></li></ul>', 'note'],
  ['err: <li>z<div></ul>', '<ul><li>z<div></ul>', 'note'],
  ['err: <li>z<div>', '<ul><li>z<div>', 'note'],
  ['err: <li>z<div>\n</ul>\n</div>', '<ul><li>z<div>\n</ul>\n</div>', 'note'],
  ['err: <li>z<div>\n</div>\n</ul>', '<ul><li>z<div>\n</div>\n</ul>', 0],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>', '<ul><li>z<div>\n</div>\n</li>\n</ul>', 0],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</li>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</li>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</ul>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</ul>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</div>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</div>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w</p>', 'note'],
  ['err: <li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w</p>\n</p>', '<ul><li>z<div>\n</div>\n</li>\n</ul>\n</p>\n<p>x</p>\n</p>\n<p>y</p>\n</p>\n<p>z</p>\n</p>\n<p>w</p>\n</p>', 'note'],
  ['err: h1 3-qatorda yopilmagan', 'a\nb\n<h1>x\n<p>y</p>', 'note'],
  ['err: h1 3-qatorda, </h2> 5-qatorda', 'a\nb\n<h1>x\n\n</h2>', 'note'],
  ['err: <img src="a\nb">', '<img src="a\nb">', 'note'],
  ['err: <img src="a\nb', '<img src="a\nb', 'note'],
  ['err: <img src="a alt="b" > (tirnoq juft, lekin xato) ', '<img src="a alt="b" >', 'note'],
  ['err: <a href="x">y</a href>', '<a href="x">y</a href>', 'note'],
  ['err: <a href="x">y</a href="x">', '<a href="x">y</a href="x">', 'note'],
  ['err: <a href="x">y</a "> keyin <p>', '<a href="x">y</a "><p>x</p>', 'note'],
  ['err: <a href="x">y</a "> keyin <p> tirnoq yopilmagan (yopuvchi tegda)', '<a href="x">y</a "<p>x</p>', 'note'],
  ['err: <a href="x">y</a > keyin', '<a href="x">y</a ><p>x</p>', 0],
  ['err: <a href="x">y</a>> keyin', '<a href="x">y</a>><p>x</p>', 0],
  ['err: <a href="x">y<</a>', '<a href="x">y<</a>', 'note'],
  ['err: <a href="x">y<<</a>', '<a href="x">y<<</a>', 'note'],
  ['err: <a href="x">y<><</a>', '<a href="x">y<><</a>', 'note'],
  ['err: <a href="x">y< a</a>', '<a href="x">y< a</a>', 'note'],
  ['err: <a href="x">y<a</a>', '<a href="x">y<a</a>', 'note'],
  ['err: <a href="x">y<a </a>', '<a href="x">y<a </a>', 'note'],
  ['err: <a href="x">y<a<b></a>', '<a href="x">y<a<b></a>', 'note'],
  ['err: <a href="x">y<a<b</a>', '<a href="x">y<a<b</a>', 'note'],
  ['err: <a href="x">y<a<b<c</a>', '<a href="x">y<a<b<c</a>', 'note'],
];
const results = [];
for (const [name, html, exp] of CASES) {
  const r = await p.evaluate((html) => { try { return window.__X.lintHtml(html); } catch (e) { return 'THROW ' + e.message; } }, html);
  const n = Array.isArray(r) ? r.length : -1;
  const status = exp === 'note' ? 'NOTE' : (n === exp ? 'ok' : (typeof exp === 'number' && exp > 0 && n > 0 ? 'ok' : 'MISMATCH'));
  results.push({ status, name, html, exp, n, r });
}
const bad = results.filter(r => r.status === 'MISMATCH'), notes = results.filter(r => r.status === 'NOTE');
console.log('TOTAL', results.length, 'MISMATCH', bad.length, 'NOTE', notes.length, 'ok', results.length - bad.length - notes.length);
for (const r of [...bad, ...notes]) console.log(`[${r.status}] ${r.name}\n     html=${JSON.stringify(r.html)}\n     n=${r.n} ${JSON.stringify(r.r)}`);
await b.close();
